export interface ItemModel{
  name: string,
  description: string,
  actual_price: string,
  sale_price: string,
  offer_start_date: string,
  offer_end_date: string,
  quantity: number,
  offer_description: string,
  brand_name: string,
  product_origin_page: string,
  catagory: string,
  sub_catagory_1: string,
  sub_catagory_2: string,
  sub_catagory_3: string,
  keywords: string,
  is_featured: boolean,
}
